import json

file_name = "analysis_methods_dictionary.json"
analysis_methods = {
    "experimenter": "chiyu",
    "probe_type":"H10_stacked",
    "motion_corrector":"kilosort_like",
    "sorter_name": "kilosort4",
    "remove_dead_channels":True,
    "analyse_good_channels_only": False,
    "interpolate_noisy_channels":True,
    "load_raw_traces": False,
    "plot_traces":False,
    "tmin_tmax": [0.0,2200.0],
    "skip_motion_correction":False,
    "load_existing_motion_info":True,
    "save_prepocessed_file": True,
    "load_prepocessed_file": False,
    "save_sorting_file": True,
    "load_sorting_file": False,
    "save_analyser_to_disc": True,
    "load_analyser_from_disc": False,
    "extract_waveform_sparse": False,
    "extract_waveform_sparse_explicit": False,
    "export_to_phy": True,
    "overwrite_existing_phy": True,
    "load_curated_spikes": True,
    "export_report": False,
    "include_MUA": True,
    "event_of_interest": "stim_onset",
    "analyse_stim_evoked_activity": True,
    "exp_place": "Zball",
    "experiment_name": "coherence",
    "temperature_data_options": "bonsai",
    "overwrite_curated_dataset": True,
    "graph_colour_code": ["r", "y", "m", "c", "k", "b", "g", "r"],
    "save_output": True,
    "fictrac_posthoc_analysis": True,
    "use_led_to_align_stimulus_timing": True,
    "align_with_isi_onset": False,
    "mark_jump_as_nan": True,
    "active_trials_only": True,
    "filtering_method": "sg_filter",
    "plotting_tbt_overview": True,
    "plotting_trajectory": False,
    "plotting_event_related_trajectory": False,
    "plotting_deceleration_accerleration": False,
    "plotting_position_dependant_fixation": False,
    "plotting_optomotor_response": True,
    "load_experiment_condition_from_database": True,
    "select_animals_by_condition": False,
    "analysis_by_stimulus_type": False,
    "camera_fps": 144,
    "trackball_radius": 50,
    "monitor_fps": 144,
    "stim_duration": [
        5,
        25,
        50
    ],
    "interval_duration": [
        5,
        25,
        50
    ],
    "analysis_window": [-5,50],
    "prestim_duration": 300,
    "stim_type": [
        -100,
        -50,
        -20,
        0,
        20,
        50,
        100
    ],
}  # plue value representing clockwise, counterclockwise is minus, then the rest is coherence leve
json_string = json.dumps(analysis_methods, indent=1)
with open(file_name, "w") as f:
    f.write(json_string)
